### ISSUE TITLE
NPM Repo deleted?

### ISSUE THREAD

**Issue by b0z1** [openculinary/i18next-gettext-loader#2]
This repo seems to be deleted from npm which caused pipelines breaking. Instead of deleteing it you could have mark it as deprecated.

**Comment by nikcorg** [comment]
Noticed the same thing. The package is no longer available using the namespaced `@openculinary/i18next-gettext-loader` name.

**Comment by jayaddison** [comment]
Thanks @b0z1 - yep, I intended for the package to remain in place, so I did deprecate it.

Even so, it seems that when the organization was deleted, the package was removed - it makes sense, I suppose (although I was hoping that it could have remained available).

FYI: this repository will be archived soon too.

**Comment by jayaddison** [comment]
Please note: as a workaround, I can offer (although maybe not yet recommend, depending on what package management software you use) that it's possible to install dependencies directly from `git` reference.

That's the approach taken in [`openculinary/frontend`](https://github.com/openculinary/frontend.git/) to migrate a webpack-based build that uses `@openculinary/i18next-gettext-loader`.

If using Yarn 1.x then one downside of that is that no integrity hash is calculated for the dependency.  The benefit and the reason for switching is that it means fewer user accounts and credentials to maintain.

See https://github.com/openculinary/frontend/compare/c57bc39d20f19eaedc6b45abc673557517be8363...679f482aa08408ac6d9d9f0380c2b02f341411e8 for the relevant changes.

**Comment by jayaddison** [comment]
Update: https://github.com/openculinary/frontend/compare/c57bc39d20f19eaedc6b45abc673557517be8363...acffe912e59ae61e6c090ac2f14ff1bbd7ace34e could be a better comparison (adds one more commit to update the `yarn.lock` file).

**Comment by jayaddison** [comment]
Talking to myself here probably, but for completeness: I think my concerns about `git` integrity when using Yarn 1.x are mostly resolved, as long as a complete `git` SHA commit reference is included in the relevant `package.json` dependency entries.

Using named `git` tags wouldn't provide the same level of guarantee (I don't think?) because the command performing the clone operation wouldn't have an input hash (the ref) that it can use to compare against the content retrieved (the working directory contents).

Whether all `git` commands perform that kind of integrity check -- and whether there are other edge cases or gaps -- I don't know.

**Comment by jayaddison** [comment]
@b0z1 I think it would be good to publish some maintenance updates of `i18next-gettext-loader`; details are included in: https://github.com/b0z1/i18next-gettext-loader/pull/1
